blank_issues_enabled: false
contact_links:
  - name: Suncord Support Server
    url: https://discord.gg/VasF3Ma4Ab
    about: If you need help regarding Suncord, please join our support server!
  - name: Suncord Installer
    url: https://github.com/verticalsync/SuncordInstaller
    about: You can find the Suncord Installer here
