name: Sync Vencord dev branch

env:
    WORKFLOW_TOKEN: ${{ secrets.PAT_TOKEN }}

    UPSTREAM_URL: "https://github.com/Vendicated/Vencord.git"
    UPSTREAM_BRANCH: "dev"

    DOWNSTREAM_URL: "https://github.com/verticalsync/Suncord.git"
    DOWNSTREAM_BRANCH: "dev"

    SPAWN_LOGS: "true"

on:
    schedule:
        - cron: "0 * * * *"
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: GitHub Sync to Upstream Repository
              uses: dchourasia/sync-upstream-repo@master
              with:
                  upstream_repo: ${{ env.UPSTREAM_URL }}
                  upstream_branch: ${{ env.UPSTREAM_BRANCH }}
                  downstream_repo: ${{ env.DOWNSTREAM_URL }}
                  downstream_branch: ${{ env.DOWNSTREAM_BRANCH }}
                  token: ${{ env.WORKFLOW_TOKEN }}
                  spawn_logs: ${{ env.SPAWN_LOGS }}
